"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
/**
 * @const
 * @namespace
 */
var NationalInstruments = window.NationalInstruments || {};
/**
 * @const
 * @namespace
 */
NationalInstruments.PackedData = NationalInstruments.PackedData || {};
/**
 * @enum
 */
NationalInstruments.PackedData.AnyValue = {
    NONE: 0, 0: 'NONE',
    PackedBooleanValue: 1, 1: 'PackedBooleanValue',
    PackedInt8Value: 2, 2: 'PackedInt8Value',
    PackedUInt8Value: 3, 3: 'PackedUInt8Value',
    PackedInt16Value: 4, 4: 'PackedInt16Value',
    PackedUInt16Value: 5, 5: 'PackedUInt16Value',
    PackedInt32Value: 6, 6: 'PackedInt32Value',
    PackedUInt32Value: 7, 7: 'PackedUInt32Value',
    PackedInt64Value: 8, 8: 'PackedInt64Value',
    PackedUInt64Value: 9, 9: 'PackedUInt64Value',
    PackedFloat32Value: 10, 10: 'PackedFloat32Value',
    PackedFloat64Value: 11, 11: 'PackedFloat64Value',
    PackedStringValue: 12, 12: 'PackedStringValue',
    PackedComplexFloat32Value: 13, 13: 'PackedComplexFloat32Value',
    PackedComplexFloat64Value: 14, 14: 'PackedComplexFloat64Value',
    PackedPathValue: 15, 15: 'PackedPathValue',
    PackedTimestampValue: 16, 16: 'PackedTimestampValue',
    PackedBlittableArrayValue: 17, 17: 'PackedBlittableArrayValue',
    PackedArrayValue: 18, 18: 'PackedArrayValue',
    PackedClusterValue: 19, 19: 'PackedClusterValue',
    PackedVariantValue: 20, 20: 'PackedVariantValue',
    PackedWaveformValue: 21, 21: 'PackedWaveformValue'
};
/**
 * @enum
 */
NationalInstruments.PackedData.AnyPackedType = {
    NONE: 0, 0: 'NONE',
    PackedScalarType: 1, 1: 'PackedScalarType',
    PackedArrayType: 2, 2: 'PackedArrayType',
    PackedClusterType: 3, 3: 'PackedClusterType'
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedScalarType = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedScalarType}
 */
NationalInstruments.PackedData.PackedScalarType.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedScalarType=} obj
 * @returns {NationalInstruments.PackedData.PackedScalarType}
 */
NationalInstruments.PackedData.PackedScalarType.getRootAsPackedScalarType = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedScalarType).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {NationalInstruments.PackedData.AnyValue}
 */
NationalInstruments.PackedData.PackedScalarType.prototype.typeType = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? /** @type {NationalInstruments.PackedData.AnyValue} */ (this.bb.readUint8(this.bb_pos + offset)) : NationalInstruments.PackedData.AnyValue.NONE;
};
/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
NationalInstruments.PackedData.PackedScalarType.prototype.type = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedScalarType.startPackedScalarType = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyValue} typeType
 */
NationalInstruments.PackedData.PackedScalarType.addTypeType = function (builder, typeType) {
    builder.addFieldInt8(0, typeType, NationalInstruments.PackedData.AnyValue.NONE);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
NationalInstruments.PackedData.PackedScalarType.addType = function (builder, typeOffset) {
    builder.addFieldOffset(1, typeOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedScalarType.endPackedScalarType = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyValue} typeType
 * @param {flatbuffers.Offset} typeOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedScalarType.createPackedScalarType = function (builder, typeType, typeOffset) {
    NationalInstruments.PackedData.PackedScalarType.startPackedScalarType(builder);
    NationalInstruments.PackedData.PackedScalarType.addTypeType(builder, typeType);
    NationalInstruments.PackedData.PackedScalarType.addType(builder, typeOffset);
    return NationalInstruments.PackedData.PackedScalarType.endPackedScalarType(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedArrayType = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedArrayType}
 */
NationalInstruments.PackedData.PackedArrayType.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedArrayType=} obj
 * @returns {NationalInstruments.PackedData.PackedArrayType}
 */
NationalInstruments.PackedData.PackedArrayType.getRootAsPackedArrayType = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedArrayType).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayType.prototype.dimensions = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @returns {boolean}
 */
NationalInstruments.PackedData.PackedArrayType.prototype.isBlittable = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};
/**
 * @param {NationalInstruments.PackedData.PackedDataType=} obj
 * @returns {NationalInstruments.PackedData.PackedDataType|null}
 */
NationalInstruments.PackedData.PackedArrayType.prototype.elementType = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataType).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedArrayType.startPackedArrayType = function (builder) {
    builder.startObject(3);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dimensions
 */
NationalInstruments.PackedData.PackedArrayType.addDimensions = function (builder, dimensions) {
    builder.addFieldInt32(0, dimensions, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isBlittable
 */
NationalInstruments.PackedData.PackedArrayType.addIsBlittable = function (builder, isBlittable) {
    builder.addFieldInt8(1, +isBlittable, +false);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} elementTypeOffset
 */
NationalInstruments.PackedData.PackedArrayType.addElementType = function (builder, elementTypeOffset) {
    builder.addFieldOffset(2, elementTypeOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayType.endPackedArrayType = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dimensions
 * @param {boolean} isBlittable
 * @param {flatbuffers.Offset} elementTypeOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayType.createPackedArrayType = function (builder, dimensions, isBlittable, elementTypeOffset) {
    NationalInstruments.PackedData.PackedArrayType.startPackedArrayType(builder);
    NationalInstruments.PackedData.PackedArrayType.addDimensions(builder, dimensions);
    NationalInstruments.PackedData.PackedArrayType.addIsBlittable(builder, isBlittable);
    NationalInstruments.PackedData.PackedArrayType.addElementType(builder, elementTypeOffset);
    return NationalInstruments.PackedData.PackedArrayType.endPackedArrayType(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedClusterType = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedClusterType}
 */
NationalInstruments.PackedData.PackedClusterType.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedClusterType=} obj
 * @returns {NationalInstruments.PackedData.PackedClusterType}
 */
NationalInstruments.PackedData.PackedClusterType.getRootAsPackedClusterType = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedClusterType).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
NationalInstruments.PackedData.PackedClusterType.prototype.fieldNames = function (index, optionalEncoding) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedClusterType.prototype.fieldNamesLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @param {NationalInstruments.PackedData.PackedDataType=} obj
 * @returns {NationalInstruments.PackedData.PackedDataType}
 */
NationalInstruments.PackedData.PackedClusterType.prototype.fieldTypes = function (index, obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataType).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedClusterType.prototype.fieldTypesLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedClusterType.startPackedClusterType = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fieldNamesOffset
 */
NationalInstruments.PackedData.PackedClusterType.addFieldNames = function (builder, fieldNamesOffset) {
    builder.addFieldOffset(0, fieldNamesOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterType.createFieldNamesVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedClusterType.startFieldNamesVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fieldTypesOffset
 */
NationalInstruments.PackedData.PackedClusterType.addFieldTypes = function (builder, fieldTypesOffset) {
    builder.addFieldOffset(1, fieldTypesOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterType.createFieldTypesVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedClusterType.startFieldTypesVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterType.endPackedClusterType = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fieldNamesOffset
 * @param {flatbuffers.Offset} fieldTypesOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterType.createPackedClusterType = function (builder, fieldNamesOffset, fieldTypesOffset) {
    NationalInstruments.PackedData.PackedClusterType.startPackedClusterType(builder);
    NationalInstruments.PackedData.PackedClusterType.addFieldNames(builder, fieldNamesOffset);
    NationalInstruments.PackedData.PackedClusterType.addFieldTypes(builder, fieldTypesOffset);
    return NationalInstruments.PackedData.PackedClusterType.endPackedClusterType(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedDataType = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedDataType}
 */
NationalInstruments.PackedData.PackedDataType.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedDataType=} obj
 * @returns {NationalInstruments.PackedData.PackedDataType}
 */
NationalInstruments.PackedData.PackedDataType.getRootAsPackedDataType = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedDataType).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {NationalInstruments.PackedData.AnyPackedType}
 */
NationalInstruments.PackedData.PackedDataType.prototype.dataTypeType = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? /** @type {NationalInstruments.PackedData.AnyPackedType} */ (this.bb.readUint8(this.bb_pos + offset)) : NationalInstruments.PackedData.AnyPackedType.NONE;
};
/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
NationalInstruments.PackedData.PackedDataType.prototype.dataType = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedDataType.startPackedDataType = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyPackedType} dataTypeType
 */
NationalInstruments.PackedData.PackedDataType.addDataTypeType = function (builder, dataTypeType) {
    builder.addFieldInt8(0, dataTypeType, NationalInstruments.PackedData.AnyPackedType.NONE);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataTypeOffset
 */
NationalInstruments.PackedData.PackedDataType.addDataType = function (builder, dataTypeOffset) {
    builder.addFieldOffset(1, dataTypeOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedDataType.endPackedDataType = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyPackedType} dataTypeType
 * @param {flatbuffers.Offset} dataTypeOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedDataType.createPackedDataType = function (builder, dataTypeType, dataTypeOffset) {
    NationalInstruments.PackedData.PackedDataType.startPackedDataType(builder);
    NationalInstruments.PackedData.PackedDataType.addDataTypeType(builder, dataTypeType);
    NationalInstruments.PackedData.PackedDataType.addDataType(builder, dataTypeOffset);
    return NationalInstruments.PackedData.PackedDataType.endPackedDataType(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBooleanValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBooleanValue}
 */
NationalInstruments.PackedData.PackedBooleanValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBooleanValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBooleanValue}
 */
NationalInstruments.PackedData.PackedBooleanValue.getRootAsPackedBooleanValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBooleanValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {boolean}
 */
NationalInstruments.PackedData.PackedBooleanValue.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBooleanValue.startPackedBooleanValue = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 */
NationalInstruments.PackedData.PackedBooleanValue.addValue = function (builder, value) {
    builder.addFieldInt8(0, +value, +false);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBooleanValue.endPackedBooleanValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBooleanValue.createPackedBooleanValue = function (builder, value) {
    NationalInstruments.PackedData.PackedBooleanValue.startPackedBooleanValue(builder);
    NationalInstruments.PackedData.PackedBooleanValue.addValue(builder, value);
    return NationalInstruments.PackedData.PackedBooleanValue.endPackedBooleanValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt8Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt8Value}
 */
NationalInstruments.PackedData.PackedInt8Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt8Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt8Value}
 */
NationalInstruments.PackedData.PackedInt8Value.getRootAsPackedInt8Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt8Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt8Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt8Value.startPackedInt8Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt8Value.addValue = function (builder, value) {
    builder.addFieldInt8(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt8Value.endPackedInt8Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt8Value.createPackedInt8Value = function (builder, value) {
    NationalInstruments.PackedData.PackedInt8Value.startPackedInt8Value(builder);
    NationalInstruments.PackedData.PackedInt8Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedInt8Value.endPackedInt8Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt8Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt8Value}
 */
NationalInstruments.PackedData.PackedUInt8Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt8Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt8Value}
 */
NationalInstruments.PackedData.PackedUInt8Value.getRootAsPackedUInt8Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt8Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt8Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt8Value.startPackedUInt8Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt8Value.addValue = function (builder, value) {
    builder.addFieldInt8(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt8Value.endPackedUInt8Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt8Value.createPackedUInt8Value = function (builder, value) {
    NationalInstruments.PackedData.PackedUInt8Value.startPackedUInt8Value(builder);
    NationalInstruments.PackedData.PackedUInt8Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedUInt8Value.endPackedUInt8Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt16Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt16Value}
 */
NationalInstruments.PackedData.PackedInt16Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt16Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt16Value}
 */
NationalInstruments.PackedData.PackedInt16Value.getRootAsPackedInt16Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt16Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt16Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt16Value.startPackedInt16Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt16Value.addValue = function (builder, value) {
    builder.addFieldInt16(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt16Value.endPackedInt16Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt16Value.createPackedInt16Value = function (builder, value) {
    NationalInstruments.PackedData.PackedInt16Value.startPackedInt16Value(builder);
    NationalInstruments.PackedData.PackedInt16Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedInt16Value.endPackedInt16Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt16Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt16Value}
 */
NationalInstruments.PackedData.PackedUInt16Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt16Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt16Value}
 */
NationalInstruments.PackedData.PackedUInt16Value.getRootAsPackedUInt16Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt16Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt16Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt16Value.startPackedUInt16Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt16Value.addValue = function (builder, value) {
    builder.addFieldInt16(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt16Value.endPackedUInt16Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt16Value.createPackedUInt16Value = function (builder, value) {
    NationalInstruments.PackedData.PackedUInt16Value.startPackedUInt16Value(builder);
    NationalInstruments.PackedData.PackedUInt16Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedUInt16Value.endPackedUInt16Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt32Value}
 */
NationalInstruments.PackedData.PackedInt32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt32Value}
 */
NationalInstruments.PackedData.PackedInt32Value.getRootAsPackedInt32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt32Value.startPackedInt32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt32Value.addValue = function (builder, value) {
    builder.addFieldInt32(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt32Value.endPackedInt32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt32Value.createPackedInt32Value = function (builder, value) {
    NationalInstruments.PackedData.PackedInt32Value.startPackedInt32Value(builder);
    NationalInstruments.PackedData.PackedInt32Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedInt32Value.endPackedInt32Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt32Value}
 */
NationalInstruments.PackedData.PackedUInt32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt32Value}
 */
NationalInstruments.PackedData.PackedUInt32Value.getRootAsPackedUInt32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt32Value.startPackedUInt32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt32Value.addValue = function (builder, value) {
    builder.addFieldInt32(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt32Value.endPackedUInt32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt32Value.createPackedUInt32Value = function (builder, value) {
    NationalInstruments.PackedData.PackedUInt32Value.startPackedUInt32Value(builder);
    NationalInstruments.PackedData.PackedUInt32Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedUInt32Value.endPackedUInt32Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt64Value}
 */
NationalInstruments.PackedData.PackedInt64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt64Value}
 */
NationalInstruments.PackedData.PackedInt64Value.getRootAsPackedInt64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedInt64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt64Value.startPackedInt64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
NationalInstruments.PackedData.PackedInt64Value.addValue = function (builder, value) {
    builder.addFieldInt64(0, value, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt64Value.endPackedInt64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt64Value.createPackedInt64Value = function (builder, value) {
    NationalInstruments.PackedData.PackedInt64Value.startPackedInt64Value(builder);
    NationalInstruments.PackedData.PackedInt64Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedInt64Value.endPackedInt64Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt64Value}
 */
NationalInstruments.PackedData.PackedUInt64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt64Value}
 */
NationalInstruments.PackedData.PackedUInt64Value.getRootAsPackedUInt64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedUInt64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt64Value.startPackedUInt64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
NationalInstruments.PackedData.PackedUInt64Value.addValue = function (builder, value) {
    builder.addFieldInt64(0, value, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt64Value.endPackedUInt64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt64Value.createPackedUInt64Value = function (builder, value) {
    NationalInstruments.PackedData.PackedUInt64Value.startPackedUInt64Value(builder);
    NationalInstruments.PackedData.PackedUInt64Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedUInt64Value.endPackedUInt64Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedFloat32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedFloat32Value}
 */
NationalInstruments.PackedData.PackedFloat32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedFloat32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedFloat32Value}
 */
NationalInstruments.PackedData.PackedFloat32Value.getRootAsPackedFloat32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedFloat32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedFloat32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedFloat32Value.startPackedFloat32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedFloat32Value.addValue = function (builder, value) {
    builder.addFieldFloat32(0, value, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat32Value.endPackedFloat32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat32Value.createPackedFloat32Value = function (builder, value) {
    NationalInstruments.PackedData.PackedFloat32Value.startPackedFloat32Value(builder);
    NationalInstruments.PackedData.PackedFloat32Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedFloat32Value.endPackedFloat32Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedFloat64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedFloat64Value}
 */
NationalInstruments.PackedData.PackedFloat64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedFloat64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedFloat64Value}
 */
NationalInstruments.PackedData.PackedFloat64Value.getRootAsPackedFloat64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedFloat64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedFloat64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedFloat64Value.startPackedFloat64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedFloat64Value.addValue = function (builder, value) {
    builder.addFieldFloat64(0, value, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat64Value.endPackedFloat64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat64Value.createPackedFloat64Value = function (builder, value) {
    NationalInstruments.PackedData.PackedFloat64Value.startPackedFloat64Value(builder);
    NationalInstruments.PackedData.PackedFloat64Value.addValue(builder, value);
    return NationalInstruments.PackedData.PackedFloat64Value.endPackedFloat64Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedStringValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedStringValue}
 */
NationalInstruments.PackedData.PackedStringValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedStringValue=} obj
 * @returns {NationalInstruments.PackedData.PackedStringValue}
 */
NationalInstruments.PackedData.PackedStringValue.getRootAsPackedStringValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedStringValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
NationalInstruments.PackedData.PackedStringValue.prototype.value = function (optionalEncoding) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedStringValue.startPackedStringValue = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedStringValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(0, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedStringValue.endPackedStringValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedStringValue.createPackedStringValue = function (builder, valueOffset) {
    NationalInstruments.PackedData.PackedStringValue.startPackedStringValue(builder);
    NationalInstruments.PackedData.PackedStringValue.addValue(builder, valueOffset);
    return NationalInstruments.PackedData.PackedStringValue.endPackedStringValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBlittableArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBlittableArrayValue}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBlittableArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBlittableArrayValue}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.getRootAsPackedBlittableArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBlittableArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensions = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensionsLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int32Array}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensionsArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.value = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int8Array}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.valueArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startPackedBlittableArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dimensionsOffset
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.addDimensions = function (builder, dimensionsOffset) {
    builder.addFieldOffset(0, dimensionsOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.createDimensionsVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt32(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startDimensionsVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.createValueVector = function (builder, data) {
    builder.startVector(1, data.length, 1);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt8(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(1, numElems, 1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.endPackedBlittableArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dimensionsOffset
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.createPackedBlittableArrayValue = function (builder, dimensionsOffset, valueOffset) {
    NationalInstruments.PackedData.PackedBlittableArrayValue.startPackedBlittableArrayValue(builder);
    NationalInstruments.PackedData.PackedBlittableArrayValue.addDimensions(builder, dimensionsOffset);
    NationalInstruments.PackedData.PackedBlittableArrayValue.addValue(builder, valueOffset);
    return NationalInstruments.PackedData.PackedBlittableArrayValue.endPackedBlittableArrayValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBlittable1DArrayValue}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBlittable1DArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBlittable1DArrayValue}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.getRootAsPackedBlittable1DArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBlittable1DArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.length = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.value = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int8Array}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.valueArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.startPackedBlittable1DArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} length
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.addLength = function (builder, length) {
    builder.addFieldInt32(0, length, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.createValueVector = function (builder, data) {
    builder.startVector(1, data.length, 1);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt8(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(1, numElems, 1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.endPackedBlittable1DArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} length
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.createPackedBlittable1DArrayValue = function (builder, length, valueOffset) {
    NationalInstruments.PackedData.PackedBlittable1DArrayValue.startPackedBlittable1DArrayValue(builder);
    NationalInstruments.PackedData.PackedBlittable1DArrayValue.addLength(builder, length);
    NationalInstruments.PackedData.PackedBlittable1DArrayValue.addValue(builder, valueOffset);
    return NationalInstruments.PackedData.PackedBlittable1DArrayValue.endPackedBlittable1DArrayValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedArrayValue}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedArrayValue}
 */
NationalInstruments.PackedData.PackedArrayValue.getRootAsPackedArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {number} index
 * @param {NationalInstruments.PackedData.PackedDataValue=} obj
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.value = function (index, obj) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensions = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensionsLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int32Array}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensionsArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedArrayValue.startPackedArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(0, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.createValueVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dimensionsOffset
 */
NationalInstruments.PackedData.PackedArrayValue.addDimensions = function (builder, dimensionsOffset) {
    builder.addFieldOffset(1, dimensionsOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.createDimensionsVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt32(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedArrayValue.startDimensionsVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.endPackedArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 * @param {flatbuffers.Offset} dimensionsOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.createPackedArrayValue = function (builder, valueOffset, dimensionsOffset) {
    NationalInstruments.PackedData.PackedArrayValue.startPackedArrayValue(builder);
    NationalInstruments.PackedData.PackedArrayValue.addValue(builder, valueOffset);
    NationalInstruments.PackedData.PackedArrayValue.addDimensions(builder, dimensionsOffset);
    return NationalInstruments.PackedData.PackedArrayValue.endPackedArrayValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedVariantValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedVariantValue}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedVariantValue=} obj
 * @returns {NationalInstruments.PackedData.PackedVariantValue}
 */
NationalInstruments.PackedData.PackedVariantValue.getRootAsPackedVariantValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedVariantValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {NationalInstruments.PackedData.PackedDataValue=} obj
 * @returns {NationalInstruments.PackedData.PackedDataValue|null}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.data = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataValue).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @param {NationalInstruments.PackedData.PackedDataType=} obj
 * @returns {NationalInstruments.PackedData.PackedDataType|null}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.dataType = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataType).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.dataSize = function () {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.attributeNames = function (index, optionalEncoding) {
    var offset = this.bb.__offset(this.bb_pos, 10);
    return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.attributeNamesLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 10);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @param {NationalInstruments.PackedData.PackedVariantValue=} obj
 * @returns {NationalInstruments.PackedData.PackedVariantValue}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.attributeValues = function (index, obj) {
    var offset = this.bb.__offset(this.bb_pos, 12);
    return offset ? (obj || new NationalInstruments.PackedData.PackedVariantValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedVariantValue.prototype.attributeValuesLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 12);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedVariantValue.startPackedVariantValue = function (builder) {
    builder.startObject(5);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
NationalInstruments.PackedData.PackedVariantValue.addData = function (builder, dataOffset) {
    builder.addFieldOffset(0, dataOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataTypeOffset
 */
NationalInstruments.PackedData.PackedVariantValue.addDataType = function (builder, dataTypeOffset) {
    builder.addFieldOffset(1, dataTypeOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dataSize
 */
NationalInstruments.PackedData.PackedVariantValue.addDataSize = function (builder, dataSize) {
    builder.addFieldInt32(2, dataSize, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributeNamesOffset
 */
NationalInstruments.PackedData.PackedVariantValue.addAttributeNames = function (builder, attributeNamesOffset) {
    builder.addFieldOffset(3, attributeNamesOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedVariantValue.createAttributeNamesVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedVariantValue.startAttributeNamesVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributeValuesOffset
 */
NationalInstruments.PackedData.PackedVariantValue.addAttributeValues = function (builder, attributeValuesOffset) {
    builder.addFieldOffset(4, attributeValuesOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedVariantValue.createAttributeValuesVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedVariantValue.startAttributeValuesVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedVariantValue.endPackedVariantValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 * @param {flatbuffers.Offset} dataTypeOffset
 * @param {number} dataSize
 * @param {flatbuffers.Offset} attributeNamesOffset
 * @param {flatbuffers.Offset} attributeValuesOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedVariantValue.createPackedVariantValue = function (builder, dataOffset, dataTypeOffset, dataSize, attributeNamesOffset, attributeValuesOffset) {
    NationalInstruments.PackedData.PackedVariantValue.startPackedVariantValue(builder);
    NationalInstruments.PackedData.PackedVariantValue.addData(builder, dataOffset);
    NationalInstruments.PackedData.PackedVariantValue.addDataType(builder, dataTypeOffset);
    NationalInstruments.PackedData.PackedVariantValue.addDataSize(builder, dataSize);
    NationalInstruments.PackedData.PackedVariantValue.addAttributeNames(builder, attributeNamesOffset);
    NationalInstruments.PackedData.PackedVariantValue.addAttributeValues(builder, attributeValuesOffset);
    return NationalInstruments.PackedData.PackedVariantValue.endPackedVariantValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedWaveformValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedWaveformValue}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedWaveformValue=} obj
 * @returns {NationalInstruments.PackedData.PackedWaveformValue}
 */
NationalInstruments.PackedData.PackedWaveformValue.getRootAsPackedWaveformValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedWaveformValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {NationalInstruments.PackedData.PackedTimestampValue=} obj
 * @returns {NationalInstruments.PackedData.PackedTimestampValue|null}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.t0 = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? (obj || new NationalInstruments.PackedData.PackedTimestampValue).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.dt = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @param {NationalInstruments.PackedData.PackedBlittable1DArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBlittable1DArrayValue|null}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.y = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? (obj || new NationalInstruments.PackedData.PackedBlittable1DArrayValue).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @param {NationalInstruments.PackedData.PackedVariantValue=} obj
 * @returns {NationalInstruments.PackedData.PackedVariantValue|null}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.attributes = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 10);
    return offset ? (obj || new NationalInstruments.PackedData.PackedVariantValue).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedWaveformValue.startPackedWaveformValue = function (builder) {
    builder.startObject(4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} t0Offset
 */
NationalInstruments.PackedData.PackedWaveformValue.addT0 = function (builder, t0Offset) {
    builder.addFieldOffset(0, t0Offset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dt
 */
NationalInstruments.PackedData.PackedWaveformValue.addDt = function (builder, dt) {
    builder.addFieldFloat64(1, dt, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} yOffset
 */
NationalInstruments.PackedData.PackedWaveformValue.addY = function (builder, yOffset) {
    builder.addFieldOffset(2, yOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributesOffset
 */
NationalInstruments.PackedData.PackedWaveformValue.addAttributes = function (builder, attributesOffset) {
    builder.addFieldOffset(3, attributesOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedWaveformValue.endPackedWaveformValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} t0Offset
 * @param {number} dt
 * @param {flatbuffers.Offset} yOffset
 * @param {flatbuffers.Offset} attributesOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedWaveformValue.createPackedWaveformValue = function (builder, t0Offset, dt, yOffset, attributesOffset) {
    NationalInstruments.PackedData.PackedWaveformValue.startPackedWaveformValue(builder);
    NationalInstruments.PackedData.PackedWaveformValue.addT0(builder, t0Offset);
    NationalInstruments.PackedData.PackedWaveformValue.addDt(builder, dt);
    NationalInstruments.PackedData.PackedWaveformValue.addY(builder, yOffset);
    NationalInstruments.PackedData.PackedWaveformValue.addAttributes(builder, attributesOffset);
    return NationalInstruments.PackedData.PackedWaveformValue.endPackedWaveformValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedComplexFloat32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedComplexFloat32Value}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedComplexFloat32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedComplexFloat32Value}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.getRootAsPackedComplexFloat32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedComplexFloat32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.prototype.real = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.prototype.imaginary = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.startPackedComplexFloat32Value = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} real
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.addReal = function (builder, real) {
    builder.addFieldFloat32(0, real, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} imaginary
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.addImaginary = function (builder, imaginary) {
    builder.addFieldFloat32(1, imaginary, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.endPackedComplexFloat32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} real
 * @param {number} imaginary
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedComplexFloat32Value.createPackedComplexFloat32Value = function (builder, real, imaginary) {
    NationalInstruments.PackedData.PackedComplexFloat32Value.startPackedComplexFloat32Value(builder);
    NationalInstruments.PackedData.PackedComplexFloat32Value.addReal(builder, real);
    NationalInstruments.PackedData.PackedComplexFloat32Value.addImaginary(builder, imaginary);
    return NationalInstruments.PackedData.PackedComplexFloat32Value.endPackedComplexFloat32Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedComplexFloat64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedComplexFloat64Value}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedComplexFloat64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedComplexFloat64Value}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.getRootAsPackedComplexFloat64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedComplexFloat64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.prototype.real = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.prototype.imaginary = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.startPackedComplexFloat64Value = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} real
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.addReal = function (builder, real) {
    builder.addFieldFloat64(0, real, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} imaginary
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.addImaginary = function (builder, imaginary) {
    builder.addFieldFloat64(1, imaginary, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.endPackedComplexFloat64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} real
 * @param {number} imaginary
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedComplexFloat64Value.createPackedComplexFloat64Value = function (builder, real, imaginary) {
    NationalInstruments.PackedData.PackedComplexFloat64Value.startPackedComplexFloat64Value(builder);
    NationalInstruments.PackedData.PackedComplexFloat64Value.addReal(builder, real);
    NationalInstruments.PackedData.PackedComplexFloat64Value.addImaginary(builder, imaginary);
    return NationalInstruments.PackedData.PackedComplexFloat64Value.endPackedComplexFloat64Value(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedPathValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedPathValue}
 */
NationalInstruments.PackedData.PackedPathValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedPathValue=} obj
 * @returns {NationalInstruments.PackedData.PackedPathValue}
 */
NationalInstruments.PackedData.PackedPathValue.getRootAsPackedPathValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedPathValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedPathValue.prototype.pathType = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
NationalInstruments.PackedData.PackedPathValue.prototype.components = function (index, optionalEncoding) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedPathValue.prototype.componentsLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedPathValue.startPackedPathValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} pathType
 */
NationalInstruments.PackedData.PackedPathValue.addPathType = function (builder, pathType) {
    builder.addFieldInt64(0, pathType, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} componentsOffset
 */
NationalInstruments.PackedData.PackedPathValue.addComponents = function (builder, componentsOffset) {
    builder.addFieldOffset(1, componentsOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedPathValue.createComponentsVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedPathValue.startComponentsVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedPathValue.endPackedPathValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} pathType
 * @param {flatbuffers.Offset} componentsOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedPathValue.createPackedPathValue = function (builder, pathType, componentsOffset) {
    NationalInstruments.PackedData.PackedPathValue.startPackedPathValue(builder);
    NationalInstruments.PackedData.PackedPathValue.addPathType(builder, pathType);
    NationalInstruments.PackedData.PackedPathValue.addComponents(builder, componentsOffset);
    return NationalInstruments.PackedData.PackedPathValue.endPackedPathValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedTimestampValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedTimestampValue}
 */
NationalInstruments.PackedData.PackedTimestampValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedTimestampValue=} obj
 * @returns {NationalInstruments.PackedData.PackedTimestampValue}
 */
NationalInstruments.PackedData.PackedTimestampValue.getRootAsPackedTimestampValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedTimestampValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedTimestampValue.prototype.seconds = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedTimestampValue.prototype.fractions = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedTimestampValue.startPackedTimestampValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} seconds
 */
NationalInstruments.PackedData.PackedTimestampValue.addSeconds = function (builder, seconds) {
    builder.addFieldInt64(0, seconds, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} fractions
 */
NationalInstruments.PackedData.PackedTimestampValue.addFractions = function (builder, fractions) {
    builder.addFieldInt64(1, fractions, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedTimestampValue.endPackedTimestampValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} seconds
 * @param {flatbuffers.Long} fractions
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedTimestampValue.createPackedTimestampValue = function (builder, seconds, fractions) {
    NationalInstruments.PackedData.PackedTimestampValue.startPackedTimestampValue(builder);
    NationalInstruments.PackedData.PackedTimestampValue.addSeconds(builder, seconds);
    NationalInstruments.PackedData.PackedTimestampValue.addFractions(builder, fractions);
    return NationalInstruments.PackedData.PackedTimestampValue.endPackedTimestampValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedClusterValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedClusterValue}
 */
NationalInstruments.PackedData.PackedClusterValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedClusterValue=} obj
 * @returns {NationalInstruments.PackedData.PackedClusterValue}
 */
NationalInstruments.PackedData.PackedClusterValue.getRootAsPackedClusterValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedClusterValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedClusterValue.startPackedClusterValue = function (builder) {
    builder.startObject(0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterValue.endPackedClusterValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterValue.createPackedClusterValue = function (builder) {
    NationalInstruments.PackedData.PackedClusterValue.startPackedClusterValue(builder);
    return NationalInstruments.PackedData.PackedClusterValue.endPackedClusterValue(builder);
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedDataValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedDataValue=} obj
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedDataValue.getRootAsPackedDataValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedDataValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {NationalInstruments.PackedData.AnyValue}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.valueType = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? /** @type {NationalInstruments.PackedData.AnyValue} */ (this.bb.readUint8(this.bb_pos + offset)) : NationalInstruments.PackedData.AnyValue.NONE;
};
/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.value = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedDataValue.startPackedDataValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyValue} valueType
 */
NationalInstruments.PackedData.PackedDataValue.addValueType = function (builder, valueType) {
    builder.addFieldInt8(0, valueType, NationalInstruments.PackedData.AnyValue.NONE);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedDataValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedDataValue.endPackedDataValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
NationalInstruments.PackedData.PackedDataValue.finishPackedDataValueBuffer = function (builder, offset) {
    builder.finish(offset);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyValue} valueType
 * @param {flatbuffers.Offset} valueOffset
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedDataValue.createPackedDataValue = function (builder, valueType, valueOffset) {
    NationalInstruments.PackedData.PackedDataValue.startPackedDataValue(builder);
    NationalInstruments.PackedData.PackedDataValue.addValueType(builder, valueType);
    NationalInstruments.PackedData.PackedDataValue.addValue(builder, valueOffset);
    return NationalInstruments.PackedData.PackedDataValue.endPackedDataValue(builder);
};
//# sourceMappingURL=PackedDataValues_generated.js.map